export interface Pbl {
  info2: string;
  info: string;
  mYSQLMode: boolean;
  id: string | null;
  limiteDecimal: string | null;
  conString: string | null;
  outgoingpassword: string;
  outgoingemail: string;
  outgoingpassword1: string;
  outgoingemail1: string;
  smtpserver: string | null;
  smtpport: number;
  tarefasStamp: string;
  direcaoGeral: string;
  docGeral: string | null;
  nomeTarefa: string | null;
  dirDepStamp: string | null;
  dirStamp: string | null;
  userTypeDescription: string | null;
  visualizainformaclassificada: boolean;
  userLogado: any;
  pathpadra: string;
  estadoJunta: string;
  processoStamp: string;
  mensagem: string;
  nomeChefe: string | null;
  patenteCategoria: string | null;
  nomeDirector: string | null;
  corpoMensagem: string;
  textJuntas: string;
  assinaturaHtml: string;
  dclinicosCorpoMensagem: string;
  protocolo: string | null;
  nomeUserLogado: string;
  conselhoTenico: boolean;
  verSitClass: boolean;
  caminhoRota: string;
  rota: string | null;
  rotaId: string | null;
  entradastamp: string;
  moedaBase: string | null;
  ctExpirado: boolean;
  rhsExpirado: boolean;
  versaoActivo: string;
  uRh: number;
  uCt: number;
  uGes: number;
  dtContas: any[];
  impressoras: any[];
  dtTirps: any[];
  cCondicao: string;
  numdoc: string;
  factstamp: string | null;
  tabela: any[];
  dtSt: any[];
  dtStPrecos: any[];
  editMode: boolean;
  numeroDoc: number;
  inserindo: boolean;
  procurou: boolean;
  servico: boolean;
  filename: string;
  nomeTabela: string;
  tdocXml: string;
  tdocNomFile: string;
  moeda: string;
  tipoDocumento: string;
  codigo: string | null;
  disciplina: string | null;
  turmastamp: string | null;
  anoSemstamp: string | null;
  etapa: string | null;
  descurso: string | null;
  ststamp: string | null;
  cursostamp: string | null;
  anosem: string | null;
  planoCurricular: any[];
  horario: any[];
  minhasNotasNestadisciplina: any[];
  dtAgendadivida: any[];
  dtturmaCl: any[];
  dtTurmas: any[];
  professoresPorDisciplina: any[];
  nivel: string | null;
  descricaoTeste: string;
  rptname: string | null;
  academia: boolean;
  sqlDate: string;
}
